[2023-04-10T12:56:07.951+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T12:56:07.981+0400] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [queued]>
[2023-04-10T12:56:07.981+0400] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T12:56:07.981+0400] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-10T12:56:07.982+0400] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T12:56:08.025+0400] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): demultiplex> on 2023-04-10 08:47:10.123376+00:00
[2023-04-10T12:56:08.038+0400] {standard_task_runner.py:55} INFO - Started process 515 to run task
[2023-04-10T12:56:08.047+0400] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '10X_sequence', 'demultiplex', 'Airflow_test_cell_ranger_10_04_2023 12_47_08', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/10X_sequence_dag.py', '--cfg-path', '/tmp/tmpnz7tov16']
[2023-04-10T12:56:08.048+0400] {standard_task_runner.py:83} INFO - Job 20: Subtask demultiplex
[2023-04-10T12:56:08.257+0400] {task_command.py:389} INFO - Running <TaskInstance: 10X_sequence.demultiplex Airflow_test_cell_ranger_10_04_2023 12_47_08 [running]> on host e286faa700a5
[2023-04-10T12:56:08.504+0400] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=10X_sequence
AIRFLOW_CTX_TASK_ID=demultiplex
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T08:47:10.123376+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=Airflow_test_cell_ranger_10_04_2023 12_47_08
[2023-04-10T12:56:08.506+0400] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demultiplex_ten.py", line 129, in run_demultiplex_task
    ssh_hook = SSHHook(ssh_conn_id='airflow_docker_ssh')
NameError: name 'SSHHook' is not defined
[2023-04-10T12:56:08.528+0400] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=10X_sequence, task_id=demultiplex, execution_date=20230410T084710, start_date=20230410T085607, end_date=20230410T085608
[2023-04-10T12:56:08.559+0400] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task demultiplex (name 'SSHHook' is not defined; 515)
[2023-04-10T12:56:08.578+0400] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-10T12:56:08.638+0400] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
